<?php

namespace AppBundle\Repository;

/**
 * AnalyticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyticsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Update total number of views
     *
     * @return bool
     * @throws \Doctrine\DBAL\DBALException
     */
    public function setTotalNumberOfViews()
    {
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare('UPDATE analytics SET view_counter = view_counter + 1;');

        return $stmt->execute();
    }

    /**
     * Return total number of views
     *
     * @return bool|string
     * @throws \Doctrine\DBAL\DBALException
     */
    public function getTotalNumberOfViews()
    {
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare('SELECT view_counter FROM analytics');
        $stmt->execute();

        return $stmt->fetchColumn(0);
    }

    /**
     * Update total number of views, returning new total
     *
     * @return bool|string
     */
    public function getUpdatedTotalNumberOfViews()
    {
        if ($this->setTotalNumberOfViews()) {
            return $this->getTotalNumberOfViews();
        }
    }
}
