<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Returns the number total of posts
     *
     * @return mixed
     * @throws \Doctrine\DBAL\DBALException
     */
    public function getTotalNumberOfPosts()
    {
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare('SELECT count(1) AS qt_posts FROM post');
        $stmt->execute();

        return $stmt->fetchColumn(0);
    }

    /**
     * Return coluns for CSV exported file
     *
     * @return array
     * @throws \Doctrine\DBAL\DBALException
     */
    public function getExportPosts()
    {
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare('SELECT title, name FROM post');
        $stmt->execute();

        return $stmt->fetchAll();
    }
}
